server:
  port: 8086

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
#          filters:
#            - AuthenticationFilter
#
        - id: group-service
          uri: lb://GROUP-SERVICE
          predicates:
            - Path=/api/groups/**
#          filters:
#            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
